In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

np.kron(A, B)

array([[ 5,  6, 10, 12],
       [ 7,  8, 14, 16],
       [15, 18, 20, 24],
       [21, 24, 28, 32]])

In [9]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [12]:
np.repeat(A, repeats=2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [14]:
np.repeat(A, repeats=2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [17]:
rs = np.random.RandomState(seed=100)
rs.rand(2, 2)

array([[0.54340494, 0.27836939],
       [0.42451759, 0.84477613]])

In [19]:
rs.randn(3, 3) # standard normal distribution

array([[ 0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562],
       [-1.11831825,  1.61898166,  1.54160517]])

In [20]:
mu = 1
sigma = 2

sigma + rs.randn(3, 3) + mu

array([[2.74812086, 2.15756426, 3.18451869],
       [3.9370822 , 3.73100034, 4.36155613],
       [2.67376194, 3.05567601, 3.22239961]])

In [28]:
X = rs.rand(100, 3)
print(np.mean(X, axis=0))
print(np.std(X, axis=0))

[0.52537413 0.43606668 0.52268272]
[0.29089731 0.29362863 0.2931707 ]


In [31]:
np.cov(X, rowvar=False, ddof=1)

array([[ 0.08547601, -0.0091206 ,  0.00026219],
       [-0.0091206 ,  0.08708866,  0.01015601],
       [ 0.00026219,  0.01015601,  0.08681723]])

In [33]:
import yfinance as yf

assets = ['AAPL', 'CSCO', 'IBM', 'AMZN']
data = yf.download(assets, start='2017-01-01', end='2019-01-01')
data.head()

[*********************100%%**********************]  4 of 4 completed


Price       Adj Close                                        Close             \
Ticker           AAPL       AMZN       CSCO         IBM       AAPL       AMZN   
Date                                                                            
2017-01-03  26.989267  37.683498  24.399662  114.304199  29.037500  37.683498   
2017-01-04  26.959059  37.859001  24.254618  115.719406  29.004999  37.859001   
2017-01-05  27.096151  39.022499  24.311012  115.336533  29.152500  39.022499   
2017-01-06  27.398235  39.799500  24.359367  115.903969  29.477501  39.799500   
2017-01-09  27.649185  39.846001  24.319082  114.618683  29.747499  39.846001   

Price                                   High             ...        Low  \
Ticker           CSCO         IBM       AAPL       AMZN  ...       CSCO   
Date                                                     ...              
2017-01-03  30.540001  159.837479  29.082500  37.938000  ...  30.209999   
2017-01-04  30.100000  161.816437  29.127501  37.984001  ...  30.020000   
2017-01-05  30.170000  161.281067  29.215000  39.119999  ...  30.070000   
2017-01-06  30.230000  162.074570  29.540001  39.972000  ...  30.030001   
2017-01-09  30.180000  160.277252  29.857500  40.088501  ...  30.080000   

Price                        Open                                    \
Ticker             IBM       AAPL       AMZN       CSCO         IBM   
Date                                                                  
2017-01-03  158.709366  28.950001  37.896000  30.370001  159.655838   
2017-01-04  160.000000  28.962500  37.919498  30.240000  160.391968   
2017-01-05  159.904404  28.980000  38.077499  30.100000  161.806885   
2017-01-06  160.152969  29.195000  39.118000  30.170000  161.271515   
2017-01-09  160.248566  29.487499  39.900002  30.219999  162.017212   

Price          Volume                                
Ticker           AAPL       AMZN      CSCO      IBM  
Date                                                 
2017-01-03  115127600   70422000  22370600  3069278  
2017-01-04   84472400   50210000  22281000  3536944  
2017-01-05   88774400  116602000  18372500  2805686  
2017-01-06  127007600  119724000  15923200  3080993  
2017-01-09  134247600   68922000  17177800  3336635  

[5 rows x 24 columns]

In [49]:
prices_pd = data.loc[:, ('Adj Close', slice(None))]
prices_pd

Price       Adj Close                                  
Ticker           AAPL       AMZN       CSCO         IBM
Date                                                   
2017-01-03  26.989267  37.683498  24.399662  114.304199
2017-01-04  26.959059  37.859001  24.254618  115.719406
2017-01-05  27.096151  39.022499  24.311012  115.336533
2017-01-06  27.398235  39.799500  24.359367  115.903969
2017-01-09  27.649185  39.846001  24.319082  114.618683
...               ...        ...        ...         ...
2018-12-24  35.187366  67.197998  34.344910   79.851288
2018-12-26  37.665310  73.544998  36.212231   82.686943
2018-12-27  37.420868  73.082001  36.587399   84.461090
2018-12-28  37.440033  73.901001  36.468021   83.904350
2018-12-31  37.801910  75.098503  36.945511   84.379448

[502 rows x 4 columns]

In [52]:
prices_pd.columns = ['AAPL', 'AMZN', 'CSCO', 'IBM']
prices_pd

AAPL       AMZN       CSCO         IBM
Date                                                   
2017-01-03  26.989267  37.683498  24.399662  114.304199
2017-01-04  26.959059  37.859001  24.254618  115.719406
2017-01-05  27.096151  39.022499  24.311012  115.336533
2017-01-06  27.398235  39.799500  24.359367  115.903969
2017-01-09  27.649185  39.846001  24.319082  114.618683
...               ...        ...        ...         ...
2018-12-24  35.187366  67.197998  34.344910   79.851288
2018-12-26  37.665310  73.544998  36.212231   82.686943
2018-12-27  37.420868  73.082001  36.587399   84.461090
2018-12-28  37.440033  73.901001  36.468021   83.904350
2018-12-31  37.801910  75.098503  36.945511   84.379448

[502 rows x 4 columns]

In [62]:
daily_returns_pd = np.log(prices_pd / prices_pd.shift(1))
daily_returns_pd.dropna(inplace=True)
daily_returns_pd

AAPL      AMZN      CSCO       IBM
Date                                              
2017-01-04 -0.001120  0.004646 -0.005962  0.012305
2017-01-05  0.005072  0.030270  0.002322 -0.003314
2017-01-06  0.011087  0.019716  0.001987  0.004908
2017-01-09  0.009118  0.001168 -0.001655 -0.011151
2017-01-10  0.001008 -0.001281  0.006605 -0.012786
...              ...       ...       ...       ...
2018-12-24 -0.026215 -0.024613 -0.038237 -0.030848
2018-12-26  0.068052  0.090254  0.052943  0.034896
2018-12-27 -0.006511 -0.006315  0.010307  0.021229
2018-12-28  0.000512  0.011144 -0.003268 -0.006613
2018-12-31  0.009619  0.016074  0.013008  0.005646

[501 rows x 4 columns]

In [66]:
mu = daily_returns_pd.mean().to_numpy()
mu

array([ 0.0006725 ,  0.0013764 ,  0.00082809, -0.00060587])

In [68]:
sigma = daily_returns_pd.std().to_numpy()
sigma

array([0.01503463, 0.01851482, 0.01372969, 0.01305533])

In [71]:
skew = daily_returns_pd.skew().to_numpy()
skew

array([-0.11676368,  0.23740979, -0.49186676, -0.61854905])

In [72]:
kurtosis = daily_returns_pd.kurtosis().to_numpy()
kurtosis

array([3.32603135, 7.03913853, 4.11345414, 9.31083125])

In [73]:
np.cov(daily_returns_pd, rowvar=False, ddof=1)

array([[2.26039970e-04, 1.73260579e-04, 1.10563145e-04, 6.85164472e-05],
       [1.73260579e-04, 3.42798706e-04, 1.41581988e-04, 8.34238324e-05],
       [1.10563145e-04, 1.41581988e-04, 1.88504316e-04, 8.48717797e-05],
       [6.85164472e-05, 8.34238324e-05, 8.48717797e-05, 1.70441711e-04]])

In [96]:
Sigma = np.cov(daily_returns_pd, rowvar=False, ddof=1)
Mu = daily_returns_pd.mean().to_numpy()
L = np.linalg.cholesky(Sigma)
Z = rs.randn(1000, 4)
Y = L @ Z.T + Mu.reshape(-1, 1)
NewSigma = np.cov(Y, ddof=1)
Y

array([[ 0.03700558,  0.00848823, -0.00807066, ...,  0.01005167,
        -0.02585648,  0.01734145],
       [ 0.03037598, -0.01953678,  0.01209264, ...,  0.02285461,
        -0.01776212,  0.03378611],
       [ 0.02436958, -0.01130354,  0.00136108, ...,  0.01694591,
         0.01142128,  0.04338997],
       [ 0.0096543 , -0.00230862,  0.00055598, ...,  0.00865667,
        -0.01058843,  0.02807276]])

In [97]:
print(f"Old Sigma: {Sigma}")
print(f"New Sigma: {NewSigma}")

Old Sigma: [[2.26039970e-04 1.73260579e-04 1.10563145e-04 6.85164472e-05]
 [1.73260579e-04 3.42798706e-04 1.41581988e-04 8.34238324e-05]
 [1.10563145e-04 1.41581988e-04 1.88504316e-04 8.48717797e-05]
 [6.85164472e-05 8.34238324e-05 8.48717797e-05 1.70441711e-04]]
New Sigma: [[2.40990840e-04 1.72526211e-04 1.01185170e-04 6.85583191e-05]
 [1.72526211e-04 3.49107584e-04 1.43975073e-04 8.85837281e-05]
 [1.01185170e-04 1.43975073e-04 1.90821116e-04 8.92414961e-05]
 [6.85583191e-05 8.85837281e-05 8.92414961e-05 1.72202595e-04]]


In [98]:
np.abs(Sigma - NewSigma).max()

1.495086914000664e-05