In [1]:
import numpy as np

### Random state for reproducibility

In [2]:
rs = np.random.RandomState(seed=100)

### Mean, standard deviation and covariance

In [22]:
num_samples = 100
num_stock_returns = 3
X = rs.rand(num_samples, num_stock_returns)  
print(f"Mean:\n", np.mean(X, axis=0))
print(f"Standard deviation:\n", np.std(X, axis=0))

"""
np.cov() assumes that each row is a variable and each column is an observation. Pass rowvar=False to indicate that each column is a variable and each row is an observation.
"""
print(f"Covariance:\n", np.cov(X, rowvar=False, ddof=1))

Mean:
 [0.50020728 0.50375054 0.51967753]
Standard deviation:
 [0.28113481 0.29302848 0.2926356 ]
Covariance:
 [[ 0.07983513 -0.00219274 -0.01044092]
 [-0.00219274  0.08673302  0.00588785]
 [-0.01044092  0.00588785  0.0865006 ]]


### Samples from uniform distribution

In [24]:
rs.rand(2, 2)

array([[0.18899771, 0.51658582],
       [0.80484256, 0.22853715]])

### Samples from standard normal distribution

In [23]:
rs.randn(3, 3)

array([[ 1.02973269e+00,  9.86687347e-03,  9.53420338e-01],
       [-5.55246923e-01,  5.22770324e-01, -1.04070697e+00],
       [ 4.82990601e-04,  1.00350734e+00, -1.24880773e+00]])

### Samples from normal distribution 

In [25]:
mu = 1
sigma = 2
sigma + rs.randn(2, 2) + mu

array([[3.56032623, 3.00476358],
       [3.18166179, 4.42104832]])

### Generating samples from normal distribution using Cholesky decomposition

Affine transformation of a normal random variable:

$$
X \sim N(\mu, \Sigma)
$$
$$
Y = AX + b
$$
$$
Y \sim N(A\mu + b, A\Sigma A^T)
$$

To generate samples from a multivariate normal distribution, we can use the following transformation:

1. Generate $X \sim N(0, I)$
2. Set $A = L$, where $L$ is the Cholesky decomposition of $\Sigma = LL^T$ and b = $\mu$
3. Compute Y = LX + $\mu$ where $Y \sim N(\mu, LIL^T)$ = $N(\mu, \Sigma)$

In [27]:
num_samples = 100
num_stock_returns = 3

X = rs.rand(num_samples, num_stock_returns)  

Sigma = np.cov(X, rowvar=False, ddof=1)
mu = np.mean(X, axis=0)

L = np.linalg.cholesky(Sigma)
Y = L@X.T + mu.reshape(-1, 1)
Y

array([[0.74989373, 0.54527613, 0.73785879, 0.6087066 , 0.54399396,
        0.63401107, 0.6437658 , 0.79034747, 0.6786374 , 0.59824243,
        0.75071186, 0.69060341, 0.6441246 , 0.76240495, 0.62972174,
        0.75084123, 0.77885065, 0.65541737, 0.67764829, 0.73825494,
        0.7316964 , 0.55201835, 0.64669317, 0.59259623, 0.55139142,
        0.67154034, 0.70997029, 0.62379383, 0.7195956 , 0.77451596,
        0.66598697, 0.75213853, 0.73936249, 0.68145896, 0.74485747,
        0.62875531, 0.74681263, 0.69769373, 0.79019423, 0.58335763,
        0.63838649, 0.59529219, 0.57437958, 0.59912234, 0.68810658,
        0.74551029, 0.63036733, 0.70182207, 0.78882885, 0.58339923,
        0.58848954, 0.72930133, 0.6718751 , 0.76943038, 0.55922146,
        0.71297024, 0.70755356, 0.69461204, 0.67328498, 0.58643421,
        0.69513451, 0.62465357, 0.59775809, 0.54140626, 0.5991382 ,
        0.76991325, 0.57126378, 0.76338053, 0.70663008, 0.58927639,
        0.6750378 , 0.53784096, 0.54287794, 0.53